/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:537c880a-4826-4c77-97dd-b0cd25b4ef03",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_u9uR5QjCe",
    "aws_user_pools_web_client_id": "lfqstp2nqb7fok0mqmjspab43",
    "oauth": {},
    "aws_content_delivery_bucket": "amplifys3final-20210428115735-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifys3final-20210428115735-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
